version: "3"
      
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    image: markitdown
    container_name: markitdown
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    command: ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]